server:
  port: 8081


spring:
  application:
    name: feign-example


management:
  zipkin:
    tracing:
      endpoint: http://158.160.65.127:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            request: true