spring:
  application:
    name: elk-example



#logging:
#  pattern:
#    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  zipkin:
    tracing:
      endpoint: http://89.169.167.43:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: 'prometheus, health'

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            request: true
  prometheus:
    metrics:
      export:
        enabled: true



server:
  port: 8080
